services:

        
    importer:
        class: ArcoVoltaico\ImportBundle\Services\Importer
        arguments: [@doctrine.orm.entity_manager, @service_container, @translator ]
        scope: prototype  